### ISSUE TITLE
Problema instalacao

### ISSUE THREAD

**Issue by pietrovieira** [prodis/correios-cep#1]
Estou tentando instalar mas tem a dependencia desta gem, mas nao instala de jeito nenhum, tem como me ajudar?

ERRO:
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

**Comment by heliohead** [comment]
Tenta

gem install nokogiri -v 1.6.5 -- --use-system-libraries

**Comment by prodis** [comment]
@pietrovieira Resolvido?

**Comment by pietrovieira** [comment]
Vou testar novamente depois, mas desde ja obrigado pela atencao :)

**Comment by prodis** [comment]
O Nokogiri é uma dependência muito grande para o que precisa nessa gem.
Estava querendo trocar pelo Ox.

Se você estiver a fim de fazer: https://github.com/prodis/correios-cep/issues/3

**Comment by prodis** [comment]
@pietrovieira 
Estou fechando a issue. Caso ainda esteja tendo o mesmo problema, reabra-a e/ou comente-a.
