### ISSUE TITLE
Erro ao procurar um endereço por CEP

### ISSUE THREAD

**Issue by prodis** [prodis/correios-cep#2]
Ao consultar um CEP para obter o endereço, o retorno é `nil` e um erro ocorre na chamada para o serviço dos Correios.

```ruby
require 'correios-cep'

Correios::CEP::AddressFinder.get '05707-001'
# => nil
```

No log:
```
I, [2015-03-20T16:59:16.484762 #29188]  INFO -- : [Correios::CEP] Request:
POST http://200.252.60.209/SigepCliente/AtendeClienteService
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/"><soapenv:Header /><soapenv:Body><cli:consultaCEP><cep>05707-001</cep></cli:consultaCEP></soapenv:Body></soapenv:Envelope>

I, [2015-03-20T16:59:16.574551 #29188]  INFO -- : [Correios::CEP] Response:
HTTP/1.1 503 Service Temporarily Unavailable
<HTML>
<HEAD>
<TITLE>Weblogic Bridge Message
</TITLE>
</HEAD>
 <BODY>
<H2>Failure of server APACHE bridge:</H2><P>
<hr>No backend server available for connection: timed out after 10 seconds or idempotent set to OFF.
<hr> </BODY>
</HTML>
```

**Comment by prodis** [comment]
# Solução
Os Correios alteraram o endereço do Web Service de consulta de endereço.

A versão **0.3.0** corrige esse problema.

**Comment by rafaelcgo** [comment]
@prodis Era bom botar um Changelog no README avisando dessas mudanças mais importantes.
Estava com a versão 0.1.4 e do nada parou de funcionar.

**Comment by prodis** [comment]
@rafaelcgo 
Todas as versões anteriores à 0.3.0 pararam de funcionar porque os Correios alteraram o endereço do Web Service de consulta de endereço.

O changelog existe desde a primeira versão:
https://github.com/prodis/correios-cep/blob/master/CHANGELOG.rdoc

**Comment by rafaelcgo** [comment]
@prodis Eu vi o arquivo, minha sugestão era só deixar mais claro, na home (README), pra facilitar. Tem algumas gems que fazem isso, deixam notificações importantes na home pra galera que já chega no desespero. Parabéns pela gem!

**Comment by prodis** [comment]
@rafaelcgo 
Por favor mande um pull request do changelog formatado no README do jeito que você imagina.
Obrigado.
