### ISSUE TITLE
A autenticacao de null falhou!

### ISSUE THREAD

**Issue by thadeu** [prodis/correios-cep#33]
Correios agora obriga a ter usuário e senha no webservice?

**Comment by alispat** [comment]
Não! Agora ele te obriga a ter um contrato com CNPJ, usuário, senha e token de API válidos!

**Comment by robinhorios** [comment]
Vou testar essa API do [Brasil Aberto](https://brasilaberto.com/)

Exemplo de chamada

`GET https://brasilaberto.com/api/v1/zipcode/12949163`

Retorno:

```
{
   "meta":{
      "currentPage":1,
      "itemsPerPage":1,
      "totalOfItems":1,
      "totalOfPages":1
   },
   "result":{
      "street":"Alameda Pintassilgo",
      "complement":"",
      "district":"Loteamento Retiro Recanto Tranquilo",
      "districtId":7087,
      "city":"Atibaia",
      "cityId":105,
      "ibgeId":3504107,
      "state":"São Paulo",
      "stateShortname":"SP",
      "zipcode":"12949163"
   }
}
```

**Comment by GabrielLima1** [comment]
Uma substituta tbm seria a `gem 'viacep'`

**Comment by thadeu** [comment]
Uma pena, obrigado pelo retorno pessoal. Agora abrir issue na firma pra resolver isso.
