### ISSUE TITLE
It's not working anymore

### ISSUE THREAD

**Issue by barbolo** [prodis/correios-cep#4]
Since last week the service has stopped working.

Have you considered using the web service provided by República Virtual?
http://www.republicavirtual.com.br/busca_de_cep/Ruby/#ruby

How did you find the current web service from Correios?

**Comment by danieltamiosso** [comment]
Yep, sometimes its works, sometimes not. Also I didn't found documentation about the correios web service.

**Comment by prodis** [comment]
@barbolo @danieltamiosso 
Please see issue https://github.com/prodis/correios-cep/issues/2.
